#
# $Id: Makefile,v 1.2 2010/05/25 00:00:00 root Exp $
#

GCC     = $(ROOTFS)/host/bin/mipsel-linux-gcc
CFLAGS  = -Wall -mips32r2 -mtune=24kf -O2 -funroll-loops -fomit-frame-pointer
LIBS    = -ltta
SRC	= tta.c

all:	$(SRC)
	$(GCC) -c $(CFLAGS) $(SRC)
	$(GCC) -o tta tta.o -L.. $(LIBS)

clean:
	rm -f tta *.o *.lo *.a

